<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Akiba.Domain.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FsCheck.Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Akiba.Domain\Akiba.Domain.csproj" />
  </ItemGroup>

</Project>
