// <auto-generated />
using System;
using Akiba.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Akiba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AkibaDbContext))]
    [Migration("20260923131801_Notifications")]
    partial class Notifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("akiba")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Akiba.Infrastructure.Identity.AkibaRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Identity.AkibaUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("accounts", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AccountingPeriodRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReopenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReopenedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReopenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReopenedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Start")
                        .IsUnique();

                    b.ToTable("accounting_periods", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ApprovalDecisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ApproverUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Decision")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId", "ApproverUserId")
                        .IsUnique();

                    b.ToTable("approval_decisions", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AttachedDocumentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("attached_documents", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AuditEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("TableName", "PrimaryKey");

                    b.ToTable("audit_entries", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BankReconciliationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateTimeOffset?>("SignedOffAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedOffByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("SignedOffByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("To")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("To");

                    b.HasIndex("BankAccountId", "From", "To")
                        .IsUnique();

                    b.ToTable("bank_reconciliations", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BankStatementLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<Guid>("BankReconciliationId")
                        .HasColumnType("uuid");

                    b.Property<string>("BankReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DecidedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("MatchedToDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("MatchedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotOursReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MatchedToId");

                    b.HasIndex("BankReconciliationId", "LineNumber")
                        .IsUnique();

                    b.ToTable("bank_statement_lines", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BorrowerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("EmploymentStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ExitedOn")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IntroducedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsLandlord")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("MembershipNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayrollNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SharesAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MembershipNumber")
                        .IsUnique()
                        .HasFilter("\"MembershipNumber\" IS NOT NULL");

                    b.HasIndex("NationalId");

                    b.HasIndex("PayrollNumber")
                        .IsUnique()
                        .HasFilter("\"PayrollNumber\" IS NOT NULL AND \"PayrollNumber\" <> ''");

                    b.ToTable("borrowers", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.DividendLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<decimal>("BasisAmount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("DividendRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SharesAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("DividendRunId", "Sequence")
                        .IsUnique();

                    b.ToTable("dividend_lines", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.DividendRunRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BankCharges")
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("BasisExplanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BasisName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComputedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ComputedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("InterestEarned")
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateTimeOffset?>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("PostedOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("WithdrawnReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year");

                    b.ToTable("dividend_runs", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.GuaranteeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GuaranteedAmount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<Guid>("GuarantorId")
                        .HasColumnType("uuid");

                    b.Property<string>("GuarantorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GuarantorPayrollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ShareValueAtSigning")
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateOnly>("SignedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GuarantorId");

                    b.HasIndex("LoanApplicationId");

                    b.HasIndex("LoanId");

                    b.ToTable("guarantees", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceDocumentKind")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDocumentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("ReversesEntryId");

                    b.ToTable("journal_entries", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("SignedAmount")
                        .HasColumnType("numeric(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId", "Sequence");

                    b.ToTable("journal_lines", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ApprovedInterest")
                        .HasColumnType("numeric(19,4)");

                    b.Property<decimal?>("ApprovedPrincipal")
                        .HasColumnType("numeric(19,4)");

                    b.Property<int?>("ApprovedTermMonths")
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovedTermScaleVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ConsiderationMonth")
                        .HasColumnType("date");

                    b.Property<int>("CutoffVersion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DeclaredGrossSalary")
                        .HasColumnType("numeric(19,4)");

                    b.Property<decimal?>("MonthlyRentalIncome")
                        .HasColumnType("numeric(19,4)");

                    b.Property<int?>("NumberOfRentalUnits")
                        .HasColumnType("integer");

                    b.Property<int>("Product")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyLocation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("RentStatementsAttached")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RequestedPrincipal")
                        .HasColumnType("numeric(19,4)");

                    b.Property<int?>("RequestedTermMonths")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("Status", "ConsiderationMonth");

                    b.ToTable("loan_applications", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChequeAmount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<DateOnly>("ChequeDrawnOn")
                        .HasColumnType("date");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ChequeSignatories")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateOnly>("DisbursedOn")
                        .HasColumnType("date");

                    b.Property<bool>("HasBeenRestructured")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Interest")
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric(19,4)");

                    b.Property<int>("Product")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceivableAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RestructuresLoanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("SettledOn")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<int>("TermScaleVersion")
                        .HasColumnType("integer");

                    b.Property<string>("VoucherReference")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LoanNumber")
                        .IsUnique();

                    b.HasIndex("RestructuresLoanId");

                    b.HasIndex("BorrowerId", "Status");

                    b.ToTable("loans", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanSecurityRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("LoanApplicationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanApplicationId");

                    b.ToTable("loan_security", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.NotificationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AboutBorrowerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("QueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AboutBorrowerId");

                    b.HasIndex("Status", "QueuedAtUtc");

                    b.ToTable("notifications", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ReceiptAllocationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AllocatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AllocatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("AllocatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReversedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId", "Sequence");

                    b.ToTable("receipt_allocations", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ReceiptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)");

                    b.Property<string>("BankStatementReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ClearedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpectedClearanceOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("IdentifiedBorrowerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("PayerNameOnSlip")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ReconciledOn")
                        .HasColumnType("date");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdentifiedBorrowerId");

                    b.HasIndex("Status", "ReceivedOn");

                    b.ToTable("receipts", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ZoneRepresentativeRow", b =>
                {
                    b.Property<Guid>("ZoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.HasKey("ZoneId", "MemberId");

                    b.ToTable("zone_representatives", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ZoneRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffice")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("zones", "akiba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "akiba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "akiba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "akiba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "akiba");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Value")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ApprovalDecisionRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", null)
                        .WithMany("Decisions")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AttachedDocumentRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.BorrowerRow", null)
                        .WithMany("Documents")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", null)
                        .WithMany("Documents")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BankReconciliationRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BankStatementLineRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.BankReconciliationRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("BankReconciliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.DividendLineRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.DividendRunRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("DividendRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.GuaranteeRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", null)
                        .WithMany("Guarantees")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanRow", null)
                        .WithMany("Guarantees")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalLineRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanRow", null)
                        .WithMany()
                        .HasForeignKey("RestructuresLoanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanSecurityRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", null)
                        .WithMany("Security")
                        .HasForeignKey("LoanApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ReceiptAllocationRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.ReceiptRow", null)
                        .WithMany("Allocations")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ZoneRepresentativeRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.ZoneRow", null)
                        .WithMany("Representatives")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Identity.AkibaRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Identity.AkibaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Identity.AkibaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Identity.AkibaRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akiba.Infrastructure.Identity.AkibaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Identity.AkibaUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BankReconciliationRow", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.BorrowerRow", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.DividendRunRow", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanApplicationRow", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Documents");

                    b.Navigation("Guarantees");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.LoanRow", b =>
                {
                    b.Navigation("Guarantees");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ReceiptRow", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.ZoneRow", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
