// <auto-generated />
using System;
using Akiba.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Akiba.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AkibaDbContext))]
    [Migration("20260917103628_InitialLedger")]
    partial class InitialLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("akiba")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AccountRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerKind")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("OwnerKind", "OwnerId");

                    b.ToTable("accounts", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.AccountingPeriodRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ClosedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ClosedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("End")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ReopenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReopenedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ReopenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReopenedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("Start")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "Start")
                        .IsUnique();

                    b.ToTable("accounting_periods", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("Narration")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("PostedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReversesEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SourceDocumentKind")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDocumentReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("ReversesEntryId");

                    b.ToTable("journal_entries", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalLineRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Narration")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<decimal>("SignedAmount")
                        .HasColumnType("numeric(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId", "Sequence");

                    b.ToTable("journal_lines", "akiba");
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", null)
                        .WithMany()
                        .HasForeignKey("ReversesEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalLineRow", b =>
                {
                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.AccountRow", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", null)
                        .WithMany("Lines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Akiba.Infrastructure.Persistence.Rows.JournalEntryRow", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
